name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install stable Rust with rustfmt and clippy
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
    - name: Format
      run: cargo fmt --all --check
    - name: Clippy
      run: cargo clippy --all-targets -- -D warnings
    - name: Test
      run: cargo test --verbose
